chief worker change required even with no tfds rstudio/keras/pull/1016
Otherwise hitting: Error in py_call_impl(callable, dots$args, dots$keywords): AttributeError: 'RCallback' object has no attribute '_chief_worker_only'